# Generated by Django 6.0 on 2026-01-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_groups_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(blank=True, help_text='0: 남성(False), 1: 여성(True)', null=True),
        ),
    ]
