# Generated by Django 6.0 on 2026-01-10 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('card_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('annual_fee_domestic', models.IntegerField(default=0)),
                ('annual_fee_overseas', models.IntegerField(default=0)),
                ('fee_waiver_rule', models.CharField(blank=True, max_length=500, null=True)),
                ('baseline_requirements_text', models.CharField(blank=True, max_length=500, null=True)),
                ('benefit_cap_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='CardBenefit',
            fields=[
                ('benefit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('benefit_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('benefit_limit', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(db_column='card_id', on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'db_table': 'card_benefits',
            },
        ),
    ]
