# Generated by Django 6.0 on 2026-01-10 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('merchant_name', models.CharField(max_length=100)),
                ('spent_at', models.DateTimeField()),
                ('benefit_received', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PAID', '결제됨'), ('CANCELLED', '결제취소')], default='PAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('user_card', models.ForeignKey(db_column='user_card_id', on_delete=django.db.models.deletion.CASCADE, to='users.usercard')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subs_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('monthly_fee', models.IntegerField()),
                ('next_billing', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', '구독중'), ('CANCELED', '구독취소')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('user_card', models.ForeignKey(db_column='user_card_id', on_delete=django.db.models.deletion.CASCADE, to='users.usercard')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
