"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta  # [설명] JWT 토큰 수명 설정에 사용
from dotenv import load_dotenv

# .env 파일 로드
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # [설명] 프로젝트 루트 경로


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')  # [설명] 환경 변수에서 비밀키 로드 (직접 하드코딩 금지)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.environ.get('DEBUG', 'True') == 'True'  # [설명] 환경 변수 기반 DEBUG 모드 설정

ALLOWED_HOSTS = []  # [설명] 배포 시에는 도메인/IP를 여기에 추가


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # [설명] 도메인 앱들
    'cards', 'users', 'category', 'chat', 'expense',

    # 외부 라이브러리
    'rest_framework',      # [설명] Django REST framework
    'corsheaders',         # [설명] CORS 설정용
    'drf_spectacular',     # [설명] OpenAPI/Swagger 문서화
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # [설명] CORS 미들웨어 (최상단에 위치 권장)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'  # [설명] 최상위 URL 설정 모듈

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # [설명] 별도 템플릿 디렉토리 사용 시 경로 추가
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'  # [설명] WSGI 진입점


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 로컬 개발용 SQLite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# MySQL 설정 (Docker 사용시)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': os.getenv('DB_NAME'),
#         'USER': os.getenv('DB_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD'),
#         'HOST': os.getenv('DB_HOST'),
#         'PORT': os.getenv('DB_PORT'),
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'  # [설명] 필요 시 'Asia/Seoul' 로 변경 가능

USE_I18N = True

USE_TZ = True  # [설명] 타임존 인식 DateTime 사용


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Django REST framework 기본 설정
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # [설명] drf-spectacular 스키마 생성기
    'DEFAULT_AUTHENTICATION_CLASSES': (  # [설명] 기본 인증 방식을 JWT로 설정
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


# Simple JWT 설정
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # [설명] 액세스 토큰 유효기간
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # [설명] 리프레시 토큰 유효기간
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,  # [설명] JWT 서명에 사용할 키 (Django SECRET_KEY 재사용)
    'AUTH_HEADER_TYPES': ('Bearer',),  # [설명] Authorization: Bearer <token>
    'USER_ID_FIELD': 'user_id',  # [설명] 커스텀 User 모델의 PK 필드명
}

# CORS 설정
CORS_ALLOW_ALL_ORIGINS = True  # [설명] 테스트용으로 모든 도메인 허용 (운영 환경에서는 제한 권장)

# 커스텀 User 모델 설정
AUTH_USER_MODEL = 'users.User'  # [설명] Django 기본 User 대신 users.User 사용

# [추가] drf-spectacular 상세 설정
SPECTACULAR_SETTINGS = {
    'TITLE': '카드 추천 서비스 API',
    'SECURITY': [{'jwtAuth': []}],
    'APPEND_COMPONENTS': {
        "securitySchemes": {
            "jwtAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
}