# Generated by Django 6.0 on 2026-01-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
