# Generated by Django 6.0 on 2026-01-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
